### PR TITLE
Feature/vitamin d sensor

### PR DESCRIPTION
**Pull request by PeetahB**
New vitamin D sensor created

### CODE REVIEW

**Comment by divyachandrabose** [comment]
Looks good, tested and working well.

**Review by divyachandrabose — COMMENTED** [review]
Tested and working well.Good job.

**Review by divyachandrabose — APPROVED** [review]

**Comment by Laxmi2022** [comment]
Tested Ok and Works as expected. Good Work !

**Review by Laxmi2022 — COMMENTED** [review]
Tested OK

**Pull request merged**
